language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  slack: avto-dev:111ajC3vtVLKFkP04MzWbdtg
  email:
    on_success: never

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --dev

script:
  - composer test
